### ISSUE TITLE
Parser send last item props to parent and peers

### ISSUE THREAD

**Issue by callogerasl** [viewsdx/morph#3]
For some reason, the parser is getting the last item props and passing them to the item above and parent. 

For example, the parser is passing the Password props to the Username (CaputureText) and to the LoginWrapper (View).
Login.view
![image](https://user-images.githubusercontent.com/26061877/32558936-ea5ad3e6-c49d-11e7-86d6-9718a71c0cfd.png)

Login.view.js
![screen shot 2017-11-08 at 15 56 41](https://user-images.githubusercontent.com/26061877/32559103-40c6b4ac-c49e-11e7-8f30-43225888712b.png)

**Comment by callogerasl** [comment]
Attaching files.
[Archive.zip](https://github.com/viewsdx/morph/files/1454543/Archive.zip)

**Comment by dariocravero** [comment]
Thanks @callogerasl! I'll dive into this asap :)

**Comment by dariocravero** [comment]
here's the video of how it got fixed, it should help understand the internals a bit more https://youtu.be/8Jks6i2AXww  :)
